name: loading_more_list_fast
description: A loading more list which supports ListView,GridView,WaterfallFlow and Slivers.
version: 7.2.5
repository: https://github.com/fluttercandies/loading_more_list

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  extended_list: ^3.0.2
  extended_list_library: ^3.0.0
  loading_more_list_library_fast: ^4.2.3
  waterfall_flow: ^3.1.1
  provider: ^6.1.5+1
  fast_immutable_collections: ^11.1.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
